name: Release CI
on:
  push:
    tags:
      - '*'

jobs:
  checks:
    uses: ./.github/workflows/run-checks.yml

  publish:
    needs: [ checks ]
    uses: ./.github/workflows/publish-release.yml
    secrets: inherit
