name: Publish website
on: [ workflow_call ]

concurrency:
  group: publish-website
  cancel-in-progress: false

jobs:
  deploy:
    if: github.repository == 'whyoleg/clozy'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
