name: Run checks
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-project:
    uses: ./.github/workflows/run-build-project.yml

  build-website:
    needs: [ build-project ]
    uses: ./.github/workflows/run-build-website.yml
